### ISSUE TITLE
Mr Do's Nightmare appears to have no zip file reference

### ISSUE THREAD

**Issue by robf228** [MiSTer-devel/Arcade-Galaxian_MiSTer#15]
All I could find was: 
zip=""

Is this a problem?

**Comment by robf228** [comment]
I am referring to the Mr. Do Nightmare.mra file containing no zip reference.

**Comment by sorgelig** [comment]
it doesn't need any zip.

**Comment by robf228** [comment]
Thank you. Sorry to bother you.

**Comment by dshadoff** [comment]
The zip reference which was causing an error on mra_rom_check script, has been corrected.  This issue should be closed.
