### ISSUE TITLE
Victory.mra seems to refer to wrong zip file

### ISSUE THREAD

**Issue by robf228** [MiSTer-devel/Arcade-Galaxian_MiSTer#16]
The referenced zips are victoryc.zip and victorycb.zip. I can't find these on the web, but victory.zip does exist.

**Comment by sorgelig** [comment]
victory.zip is for completely different arcade.

**Comment by tjanas** [comment]
> The referenced zips are victoryc.zip and victorycb.zip. I can't find these on the web

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=victoryc

Close this issue?
