### ISSUE TITLE
Black Hole.mra is apparently broken XML

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Arcade-Galaxian_MiSTer#17]
**/media/fat/Scripts/mra_rom_check.sh** says:
```
There are issues with one or more of your MRA or MAME files

Please gently encourage Developers and Maintainers of MRA files to correct files with broken XML, missing CRC values and missing MAME versions values to correct their MRA files
```

**/tmp/mra_rom_check.log** says:
```
Broken XML:/media/fat/_Arcade/Black Hole.mra
```

**Comment by c0d3h4x0r** [comment]
I'm guessing this may be due to the unescaped `/` character used inside the `category` field and/or the unescaped `&` character used inside the `manufacturer` field.

**Comment by dshadoff** [comment]
Fix submitted and pull request issued.  Should be integrated soon.
