### ISSUE TITLE
Clean Sweep (TTL).mra contains information about a wrong game

### ISSUE THREAD

**Issue by Thelypody** [MiSTer-devel/Arcade-Galaxian_MiSTer#38]
Recently many .mra files across all arcade cores were updated with new tags containing additional information about the games. This led to a peculiar mix up as Clean Sweep, a homebrew port of a Vectrex game to Galaxian hardware was mistaken for an unrelated eponymous TTL game from 1974, leading to false info being fed into .mra file.

**Comment by tacertain** [comment]
Created https://github.com/MiSTer-devel/Arcade-Galaxian_MiSTer/pull/49 to address
