### ISSUE TITLE
King and balloon (US) Speeches has been removed

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Arcade-Galaxian_MiSTer#45]
Hi @misteraddons,

The speeches has been removed in this PR for the US MRA of King and Balloon.
https://github.com/MiSTer-devel/Arcade-Galaxian_MiSTer/pull/36/commits/72f325c43c2e2e3b2848a5d83b99d0b42d96ffa2

This part need to be added for speeches but I'm not sure how to follow your layout of MRA.
                
  >              <part crc="15dd5b16" name="kb2-1"/>
>		<part repeat="0x0FE0">00</part>
>		<part crc="5be2c80a" name="kbe1.ic4"/>
>		<part crc="bb59e965" name="kbe2.ic5"/>
>		<part crc="fbc7d286" name="kbe3.ic6"/>
>		<part crc="bb59e965" name="kbe2.ic7"/>

You can see in this discussion on the forum.
https://misterfpga.org/viewtopic.php?p=30398#p30398

Thanks for your time.
Wwark

**Comment by misteraddons** [comment]
Pull request submitted with fix. Thanks for finding this!

https://github.com/MiSTer-devel/Arcade-Galaxian_MiSTer/pull/46/commits/a4673abd97288860902ead127ea34d77d0bf6466

**Comment by wwark** [comment]
Thanks for the quick fix :+1:

**Comment by misteraddons** [comment]
Thanks for tracking this down for me :)
